import 'package:discount_app/model/beauty_model.dart';

class getBeauty {
  static final List<BeautyModel> Beauty = [
    BeautyModel(
      name: 'SEPHORA',
      image: 'assets/images/beauty1.jpeg',
      location: '557 Broadway',
      percentage: '20% off',
      distance: '500m',
      logo: 'assets/images/sephora.jpg',
      hour: 'Closed at 8PM',
      discountImage: [
        'assets/images/sephora_discount_1.jpg',
        'assets/images/sephora_discount_2.jpg',
        'assets/images/sephora_discount_3.jpg',
      ],
      discountTitle: [
        '25% off',
        '20% off',
        '10% off',
      ],
      discountDetail: [
        '25% off of First Brow Purchase',
        '20% off of All Purchases',
        '10% off. Valid Friday - Monday',
      ],
      qrCode: 'assets/images/qrCode.jpg',
    ),
    BeautyModel(
      name: 'MAC',
      image: 'assets/images/beauty2.jpeg',
      location: '506 Broadway',
      percentage: '15% off',
      distance: '500m',
      logo: 'assets/images/mac.jpeg',
      hour: 'Closed at 7PM',
      discountImage: [
        'assets/images/sephora_discount_1.jpg',
        'assets/images/sephora_discount_2.jpg',
        'assets/images/sephora_discount_3.jpg',
      ],
      discountTitle: [
        '25% off',
        '20% off',
        '10% off',
      ],
      discountDetail: [
        '25% off of First Brow Purchase',
        '20% off of All Purchases',
        '10% off. Valid Friday - Monday',
      ],
      qrCode: 'assets/images/qrCode.jpg',
    ),
    BeautyModel(
      name: 'Akan Cosmetics',
      image: 'assets/images/beauty3.jpeg',
      location: '420 W Broadway',
      percentage: '10% off',
      distance: '300m',
      logo: 'assets/images/sephora.jpg',
      hour: 'Closed at 8PM',
      discountImage: [
        'assets/images/sephora_discount_1.jpg',
        'assets/images/sephora_discount_2.jpg',
        'assets/images/sephora_discount_3.jpg',
      ],
      discountTitle: [
        '25% off',
        '20% off',
        '10% off',
      ],
      discountDetail: [
        '25% off of First Brow Purchase',
        '20% off of All Purchases',
        '10% off. Valid Friday - Monday',
      ],
      qrCode: 'assets/images/qrCode.jpg',
    ),
    BeautyModel(
      name: 'East 6th St Barber Shop',
      image: 'assets/images/beauty4.jpeg',
      location: '216 E 6th St',
      percentage: '\$10 off',
      distance: '200m',
      logo: 'assets/images/sephora.jpg',
      hour: 'Closed at 8PM',
      discountImage: [
        'assets/images/sephora_discount_1.jpg',
        'assets/images/sephora_discount_2.jpg',
        'assets/images/sephora_discount_3.jpg',
      ],
      discountTitle: [
        '25% off',
        '20% off',
        '10% off',
      ],
      discountDetail: [
        '25% off of First Brow Purchase',
        '20% off of All Purchases',
        '10% off. Valid Friday - Monday',
      ],
      qrCode: 'assets/images/qrCode.jpg',
    ),
    BeautyModel(
      name: 'B & H Barber',
      image: 'assets/images/beauty5.jpeg',
      location: '199 E 4th St',
      percentage: '\$5 off',
      distance: '700m',
      logo: 'assets/images/sephora.jpg',
      hour: 'Closed at 8PM',
      discountImage: [
        'assets/images/sephora_discount_1.jpg',
        'assets/images/sephora_discount_2.jpg',
        'assets/images/sephora_discount_3.jpg',
      ],
      discountTitle: [
        '25% off',
        '20% off',
        '10% off',
      ],
      discountDetail: [
        '25% off of First Brow Purchase',
        '20% off of All Purchases',
        '10% off. Valid Friday - Monday',
      ],
      qrCode: 'assets/images/qrCode.jpg',
    ),
    BeautyModel(
      name: '@ The Salon',
      image: 'assets/images/beauty6.jpeg',
      location: '54 E 4th St',
      percentage: '10% off',
      distance: '400m',
      logo: 'assets/images/sephora.jpg',
      hour: 'Closed at 8PM',
      discountImage: [
        'assets/images/sephora_discount_1.jpg',
        'assets/images/sephora_discount_2.jpg',
        'assets/images/sephora_discount_3.jpg',
      ],
      discountTitle: [
        '25% off',
        '20% off',
        '10% off',
      ],
      discountDetail: [
        '25% off of First Brow Purchase',
        '20% off of All Purchases',
        '10% off. Valid Friday - Monday',
      ],
      qrCode: 'assets/images/qrCode.jpg',
    ),
    BeautyModel(
      name: 'Arte Salon Inc',
      image: 'assets/images/beauty7.jpeg',
      location: '294 Elizabeth St',
      percentage: '20% off',
      distance: '450m',
      logo: 'assets/images/sephora.jpg',
      hour: 'Closed at 8PM',
      discountImage: [
        'assets/images/sephora_discount_1.jpg',
        'assets/images/sephora_discount_2.jpg',
        'assets/images/sephora_discount_3.jpg',
      ],
      discountTitle: [
        '25% off',
        '20% off',
        '10% off',
      ],
      discountDetail: [
        '25% off of First Brow Purchase',
        '20% off of All Purchases',
        '10% off. Valid Friday - Monday',
      ],
      qrCode: 'assets/images/qrCode.jpg',
    ),
  ];
}
